services:
  todolist-api:
    container_name: todolist-api-container
    build:
      context: .
      dockerfile: ./TodoListAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # УДАЛЯЕМ ОТСЮДА СТРОКУ ПРО JWT_KEY
      - ConnectionStrings__DefaultConnection=Server=todolist-db;Database=TodoListDB;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY} # <-- РАСКОММЕНТИРУЙ
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - todolist-db

  # Сервис для базы данных MS SQL Server
  todolist-db: # <-- 1. Имя сервиса стало более осмысленным
    container_name: todolist-mssql-container # <-- 2. Задаем статичное и понятное имя контейнера
    image: mcr.microsoft.com/mssql/server:2022-latest # <-- 5. Используем официальный образ напрямую
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD} # Переменная берется из .env
    ports:
      - "1433:1433"
    volumes:
      - todolist-db-data:/var/opt/mssql # <-- 6. Том для данных тоже переименован

# Раздел для именованных томов
volumes:
  todolist-db-data: {} # <-- 6. Объявляем наш переименованный том